version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=universidad-techemt-db
      - DB_HOST=mysql
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - .:/usr/src/app
    command: npm run dev

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: universidad-techemt-db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  migrator:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=universidad-techemt-db
      - DB_HOST=mysql
    user: '${UID}:${GID}'
    volumes:
      - ./migrations:/usr/src/app/migrations
      - ./seeders:/usr/src/app/seeders
    command: npx sequelize-cli db:migrate

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  db-data:
  rabbitmq-data:
